### PR TITLE
Chapter 3: Mostly static pages

### PR DESCRIPTION
**Pull request by anhquoc831997**

### CODE REVIEW

**Comment by anhquoc831997** [comment]
ready

**Comment by anhquoc831997** [comment]
image

**Comment by anhquoc831997** [comment]
ready

**Comment by anhquoc831997** [comment]
ready

**Comment by anhquoc831997** [comment]
ready

**Comment by anhquoc831997** [comment]
ready

**Comment by phamvanbk11** [comment]
merged

**Pull request merged**
